@host = http://127.0.0.1:8080/v1


### Login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
  

### Token verification
GET {{host}}/verify-token?eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUzODExNjgyfQ.0SnBStNQ2oEDOTvp60LHCelCjMaaPrtEe3W-yJJkioY HTTP/1.1

