@host = http://127.0.0.1:8080/v1


### Login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
  

### Token verification
GET {{host}}/verify-token?token=dyNi6lQiQGFhK2yembj2EJjmi0XcEbwfAifeeDMp0QJVIRw3iRw1bWOMbJkPOFKIwDi.i7IXoeoO.ISyJAJDV4ytaUbWykZJ-9I0iUON6ujCZvUOIyLVUI_ei7eQ-Gcij81zCWBs91cxWKh HTTP/1.1

