@host = http://127.0.0.1:8080/v1


### Login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
  

### Token verification
GET {{host}}/verify-token?eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjU0MDY2MDA4fQ.92n49wA6EPXWDTAdiLD1MjkpQ5P2whNbuVqw0_gCKSE HTTP/1.1

